`timescale 1ns / 1ps

module npu_testbench;
    logic clk, rst_n;
    logic signed [7:0] act_in [4095:0];
    logic [1:0] weight_in [4095:0];
    logic valid_in;
    logic signed [20:0] Y_rtl;
    logic valid_out;

    npu_array_4096 dut (.*);

    initial begin
        clk = 0;
        forever #5 clk = ~clk;
    end

    initial begin
        // Read input vectors from file (generated by python)
        // For simple test, we drive via force or file I/O
        $readmemb("act_in.bin", act_in);
        $readmemb("weight_in.bin", weight_in);
        
        rst_n = 0; #10; rst_n = 1;
        valid_in = 1; #10;
        valid_in = 0;
        
        #20;
        $display("%d", Y_rtl);
        $finish;
    end
endmodule
