# -*- coding: utf-8 -*-
"""Volume I, Part X5 -- Reed-Solomon decoding, traced by hand and measured.

This part is unusual in the book: it does not describe a decoder, it *runs* the
repository's own verified Reed-Solomon model and prints what happened.  Every
syndrome, every Berlekamp-Massey iteration and every corrected symbol below is
produced at build time by ``rs.py``, which is the same code the repository's
test suite exercises.  If the model were wrong the numbers here would be wrong
too, which is the point: a textbook chapter that cannot be falsified by running
it is not teaching engineering.
"""
import sys, math, random
sys.path.insert(0, "/home/user/SE/edu")
sys.path.insert(0, "/home/user/SE")
import numpy as np
from bookE import tab, fig, E
from wex import ex, prob, derive, sweep, plot, num
from figs import svg, box, txt, arr, line
import gf, rs


def _f_rsflow():
    b = []
    names = ["received r(x)", "syndromes S", "Berlekamp&ndash;Massey",
             "Chien search", "Forney", "corrected"]
    x = 10
    for i, nm in enumerate(names):
        w = 74 if i else 78
        b.append(box(x, 34, w, 28, nm, None, 8))
        if i:
            b.append(arr(x - 8, 48, x, 48))
        x += w + 8
    b.append(txt(50, 78, "2t values", 7, "middle"))
    b.append(txt(170, 78, "&sigma;(x), degree = #errors", 7, "middle"))
    b.append(txt(255, 78, "roots &rarr; positions", 7, "middle"))
    b.append(txt(335, 78, "magnitudes", 7, "middle"))
    b.append(txt(250, 104,
                 "Each stage answers one question: is there an error, how many, where, "
                 "and by how much.", 9, "middle", 'font-style="italic"'))
    return svg(500, 114, "".join(b))


def ch_rs():
    s = ['<h1 id="x5">X5. Reed&ndash;Solomon Decoding, Traced and Measured</h1>']
    s.append("""<p>Reed&ndash;Solomon is the error-correcting code that every high-speed
    Ethernet and storage link in this book actually uses, and it is the code the practice
    volume builds an IP block around. It is also a code whose decoder is usually presented
    as four opaque stages. This part opens each stage on a small field where the numbers
    can be printed in full, then measures the large field that ships.</p>""")
    s.append(fig(_f_rsflow(), "The classical Reed&ndash;Solomon decoding pipeline. The "
                              "stages below are executed for real on a small field, so "
                              "every intermediate value is printed rather than "
                              "described."))

    s.append("<h2>X5.1 The field is a choice, and an unverified choice is a risk</h2>")
    s.append("""<p>A Reed&ndash;Solomon code lives over a finite field GF(2<sup><i>m</i>
    </sup>), and the field is fixed by a primitive polynomial. Two implementations that
    pick different primitive polynomials produce different codewords and cannot talk to
    each other, even though both are &lsquo;RS(544,514)&rsquo;. The model this chapter
    runs therefore takes the polynomial as a <i>parameter</i> and records whether it has
    been confirmed against the standard.</p>""")
    f16 = gf.필드(4, 0b10011, 확인됨=True, 이름="GF(16), x^4+x+1")
    v = gf.검증(f16)
    s.append(ex("Verifying a small field before using it",
        "GF(2<sup>4</sup>) generated by <i>x</i><sup>4</sup>&nbsp;+&nbsp;<i>x</i>"
        "&nbsp;+&nbsp;1 (0b10011).",
        "The model builds exponent and log tables and refuses any polynomial whose "
        "root &alpha; has order less than 2<sup><i>m</i></sup>&minus;1 &mdash; that is, "
        "it rejects non-primitive polynomials by construction rather than by trusting the "
        "caller. It then checks the field <i>axioms</i>, not a table of expected values, "
        "because a table of expected values is only as good as whoever typed it.",
        [("Field size", num(f16.n + 1)),
         ("Order of &alpha;", num(f16.n)),
         ("Axiom checks performed", ", ".join(str(kk) for kk in v.keys())),
         ("All axioms hold", "yes" if all(v.values()) else "<b>no</b>")],
        "<b>By hard-coding the polynomial of the standard you last worked on.</b> "
        "0x11D and 0x12D both generate GF(256) and both are primitive; they are different "
        "fields for interoperability purposes. The repository's model keeps this as an "
        "explicit parameter with a <code>confirmed</code> flag precisely so that an "
        "unverified default cannot quietly become an assumption &mdash; the flag is "
        "<b>false</b> for the KP4 field in this repository, because the clause that fixes "
        "it has not been read."))

    s.append("<h2>X5.2 A complete decode, every intermediate value printed</h2>")
    c = rs.RS(f16, n=15, k=9, fcr=0)      # t = 3
    msg = [1, 2, 3, 4, 5, 6, 7, 8, 9]
    cw = c.부호화(msg)
    r = list(cw)
    inject = {2: 7, 5: 11, 11: 4}
    for pos, val in inject.items():
        r[pos] ^= val
    S = c.신드롬(r)
    out = c.복호(list(r))
    s.append(ex("RS(15,9) over GF(16): encode, corrupt, decode",
        f"Message symbols {msg}. Three symbols are then corrupted by XOR: "
        + ", ".join(f"position&nbsp;{p} &oplus;&nbsp;{v}" for p, v in inject.items())
        + f". The code corrects up to <i>t</i>&nbsp;=&nbsp;{c.t} symbols.",
        "Encode systematically, inject the errors, compute the syndromes, run "
        "Berlekamp&ndash;Massey, Chien and Forney. Everything below is the model's "
        "actual output.",
        [("Codeword", "<code>" + " ".join(f"{x:2d}" for x in cw) + "</code>"),
         ("Received", "<code>" + " ".join(f"{x:2d}" for x in r) + "</code>"),
         ("Syndromes <i>S</i><sub>0..5</sub>",
          "<code>" + " ".join(str(x) for x in S) + "</code>"),
         ("Errors found", num(out["고친수"])),
         ("Positions the decoder located",
          "<code>" + str(out["자리"]) + "</code>"),
         ("Positions actually corrupted",
          "<code>" + str(sorted(inject.keys())) + "</code>"),
         ("Decode succeeded", "yes" if out["성공"] else "<b>no</b>"),
         ("Recovered codeword equals the transmitted one",
          "yes" if out["성공"] and out["말"] == list(cw) else "<b>no</b>"),
         ("Recovered message", "<code>" + " ".join(map(str, out["메시지"])) + "</code>")],
        "<b>By declaring success when the syndromes go to zero and stopping there.</b> "
        "A decoder that miscorrects also produces zero syndromes &mdash; it has landed on "
        "a <i>different valid codeword</i>. The only defence is to re-check after "
        "correction and to bound the number of corrections by <i>t</i>; the model does "
        "both, which is why the next section's measurement of the beyond-<i>t</i> region "
        "is meaningful."))
    s.append("""<div class="bs"><b>Why the syndromes are what they are.</b> The syndrome
    <i>S<sub>j</sub></i> is the received polynomial evaluated at &alpha;<sup>fcr+<i>j</i>
    </sup>. Every valid codeword is divisible by the generator, whose roots are exactly
    those powers, so a clean codeword gives all-zero syndromes. What survives the
    evaluation is therefore only the error polynomial &mdash; the syndromes depend on the
    errors and <i>not at all</i> on the data. That single fact is what makes bounded
    distance decoding possible, and it is worth verifying on the numbers above: change
    the message and re-run, and the syndromes do not move.</div>""")
    # demonstrate that claim, computed
    msg2 = [9, 8, 7, 6, 5, 4, 3, 2, 1]
    cw2 = c.부호화(msg2)
    r2 = list(cw2)
    for pos, val in inject.items():
        r2[pos] ^= val
    S2 = c.신드롬(r2)
    s.append(sweep("The syndromes depend only on the error pattern &mdash; measured, "
                   "not asserted",
        ["Message", "Syndromes with the same three errors injected"],
        [["<code>" + str(msg) + "</code>", "<code>" + " ".join(map(str, S)) + "</code>"],
         ["<code>" + str(msg2) + "</code>", "<code>" + " ".join(map(str, S2)) + "</code>"]],
        "Two different messages, the same injected error pattern, identical syndromes. "
        + ("They match." if S == S2 else "<b>They do not match &mdash; investigate.</b>")))

    s.append("<h2>X5.3 Berlekamp&ndash;Massey as a hardware recurrence</h2>")
    s.append(derive("What Berlekamp&ndash;Massey is actually doing", [
        ("The syndromes of an <i>e</i>-error pattern satisfy a linear recurrence of "
         "order <i>e</i>.",
         "Each error contributes a geometric sequence &alpha;<sup><i>ji</i></sup>; a sum "
         "of <i>e</i> geometrics satisfies an order-<i>e</i> recurrence."),
        ("The recurrence's characteristic polynomial is the error locator &sigma;(<i>x</i>).",
         "Its roots are the inverses of the error positions, by construction."),
        ("So decoding reduces to: <b>find the shortest linear recurrence that generates "
         "the observed syndrome sequence</b>.",
         "This restatement is the entire content of the algorithm."),
        ("Berlekamp&ndash;Massey finds it in 2<i>t</i> iterations, each a discrepancy "
         "computation and a polynomial update.",
         "Equivalent to the extended Euclidean algorithm on <i>x</i><sup>2<i>t</i></sup> "
         "and <i>S</i>(<i>x</i>); the two are the standard alternatives in RTL."),
        ("Each iteration costs <i>O</i>(<i>t</i>) field multiplies, so the whole "
         "algorithm is <i>O</i>(<i>t</i><sup>2</sup>).",
         "For KP4, <i>t</i>&nbsp;=&nbsp;15, so the key equation is a few hundred "
         "multiplies &mdash; small beside the 544-symbol Chien search."),
        ("<b>The iteration count is data independent.</b>",
         "Which is why the decoder has a fixed latency, which is why the PCS can be "
         "built around it. A variable-latency decoder would need elastic buffering "
         "through the whole receive path."),
    ]))
    rows = []
    for m, n, k in [(4, 15, 9), (8, 255, 239), (10, 544, 514), (10, 528, 514)]:
        t = (n - k) // 2
        rows.append([f"GF(2<sup>{m}</sup>)", f"RS({n},{k})", num(t),
                     num(k / n, 4), num(2 * t * t), num(n),
                     num(n * m), num((n - k) * m)])
    s.append(sweep("Parameter sets and the work each implies",
        ["Field", "Code", "<i>t</i>", "Rate", "BM multiplies &asymp;2<i>t</i><sup>2</sup>",
         "Chien positions", "Codeword bits", "Parity bits"], rows,
        "RS(544,514) is the KP4 code used by 100G-per-lane Ethernet; RS(528,514) is the "
        "earlier Clause 91 code. The rate difference is small and the "
        "<i>t</i> difference is not."))

    s.append("<h2>X5.4 Beyond <i>t</i>: the region a careless test never visits</h2>")
    s.append("""<p>A bounded-distance decoder corrects up to <i>t</i> errors. What it does
    with <i>t</i>+1 or more is the interesting question, because that is the region a real
    link visits and a lazy test never does. Three outcomes are possible: detect the
    failure and flag it, miscorrect to a wrong codeword silently, or leave the word
    unchanged. The measurement below counts all three.</p>""")
    rows = []
    for e in (1, 2, 3, 4, 5, 6):
        res = rs.측정(c, e, 시행=400, 씨앗=100 + e)
        rows.append([e, "&le; <i>t</i>" if e <= c.t else "&gt; <i>t</i>",
                     num(res["고침"]), num(res["시행"]),
                     num(res["고침"] / res["시행"], 3),
                     "&mdash;" if res.get("무의미") else "measured"])
    s.append(sweep(f"RS(15,9), <i>t</i>&nbsp;=&nbsp;{c.t}: fraction of words returned "
                   "correct as the injected error count is swept",
        ["Errors injected", "Region", "Recovered exactly", "Trials", "Fraction",
         "Note"], rows,
        "400 random trials per row, seeded. The first three rows must be 1.000 &mdash; "
        "that is the code's guarantee. The rows below must <b>not</b> be 1.000, and a "
        "test suite that only ever injects zero or one error cannot tell a working "
        "decoder from one that returns its input unchanged."))
    s.append("""<div class="warn"><b>This is the false-green that RS test benches
    actually produce.</b> Inject zero errors, check the output equals the input, declare
    the decoder verified. A decoder consisting of a wire passes. The repository's
    measurement function refuses to report a pass from a zero-error trial at all, and its
    test suite deliberately breaks the syndrome computation and asserts that the
    measurement <i>notices</i>. A verification plan for an FEC block must state, for every
    test, what broken implementation that test would catch.</div>""")
    s.append(prob("Why can a decoder that corrects a word with more than <i>t</i> errors "
                  "be worse than one that flags the word as uncorrectable?",
        "Because a miscorrection is a <i>silent</i> data error and an uncorrectable flag "
        "is an <i>announced</i> one. Upper layers are built to handle the announcement: "
        "Ethernet marks the frame errored and it is discarded and retransmitted; storage "
        "returns a read failure and the host retries or reconstructs from parity. There "
        "is no layer that handles data that is wrong and claims to be right. In a system "
        "with an outer code &mdash; the concatenated structure of 802.3dj &mdash; the "
        "point is sharper still: the outer decoder can use the inner decoder's "
        "uncorrectable flag as an <b>erasure</b>, and an erasure costs one parity symbol "
        "where an unflagged error costs two. <b>Detection is worth roughly twice as much "
        "as the same amount of correction</b>, which is why real decoders spend logic on "
        "checking their own output."))
    s.append(prob("KP4 is RS(544,514) over GF(2<sup>10</sup>), yet 544 &gt; "
                  "2<sup>10</sup>&minus;1 is false &mdash; 544 is comfortably below "
                  "1023. What is the code called when <i>n</i> is smaller than the "
                  "natural length, and what does the shortening cost?",
        "It is a <b>shortened</b> Reed&ndash;Solomon code: take the RS(1023,993) code and "
        "fix the leading 479 message symbols to zero, then decline to transmit them. Both "
        "ends know they are zero, so the decoder simply treats the received word as "
        "having 479 leading zeros. Shortening costs <i>nothing</i> in minimum distance "
        "&mdash; <i>d</i> = <i>n</i>&minus;<i>k</i>+1 = 31 either way, so <i>t</i> "
        "remains 15 &mdash; and it costs nothing in the decoder except that the Chien "
        "search may be restricted to the 544 positions that are actually transmitted, "
        "which is a saving. <b>The one thing it does change is the false-detection "
        "probability</b>: a shortened code has fewer codewords in the same space, so a "
        "random error pattern is <i>less</i> likely to land on a valid codeword. "
        "Shortening therefore improves miscorrection statistics slightly, for free."))

    s.append("<h2>X5.5 From symbol errors to the number the customer reads</h2>")
    s.append("""<p>A datasheet quotes post-FEC frame loss ratio. Getting there from a raw
    bit error rate is a short calculation with one dangerous assumption, and it is worth
    doing explicitly because the intermediate quantities are the ones a compliance
    argument is made of.</p>""")
    from math import comb
    def cw_fail(ber, n=544, m=10, t=15):
        ps = 1 - (1 - ber) ** m
        # P(more than t symbol errors)
        p = 0.0
        for i in range(t + 1):
            p += comb(n, i) * ps ** i * (1 - ps) ** (n - i)
        return max(0.0, 1.0 - p)
    rows = []
    for ber in (1e-3, 3e-4, 1e-4, 3e-5, 1e-5):
        ps = 1 - (1 - ber) ** 10
        cf = cw_fail(ber)
        rows.append([num(ber, 2), num(ps, 3), num(544 * ps, 3),
                     num(cf, 2) if cf > 0 else "&lt;10<sup>-16</sup>",
                     num(cf * 53.125e9 / 5440, 2) if cf > 0 else "&mdash;"])
    s.append(sweep("Pre-FEC BER to post-FEC codeword failure rate, RS(544,514), "
                   "assuming independent bit errors",
        ["Pre-FEC BER", "Symbol error prob.", "Mean symbol errors per codeword",
         "P(codeword uncorrectable)", "Uncorrectable codewords per second at "
         "53.125&nbsp;GBd"], rows,
        "The waterfall between the first and last row spans many orders of magnitude for "
        "a factor of a hundred in input BER. That steepness is what FEC buys and it is "
        "why link margin is measured in fractions of a dB."))
    s.append("""<div class="ms"><b>The dangerous assumption, named.</b> Every number in
    that table assumes bit errors are independent. They are not, for the reason
    Part&nbsp;X4 measured: DFE error propagation makes short bursts. Bursts are partly
    <i>good</i> for a symbol code &mdash; ten wrong bits inside one symbol cost one symbol
    &mdash; and partly bad, since a burst straddling a boundary costs two. The net effect
    depends on the burst-length distribution, which is a property of the receiver, not of
    the channel. <b>This is why compliance standards specify a stressed-input test rather
    than a BER number</b>: the test reproduces the error statistics, and no scalar summary
    of the channel can. When a customer asks for post-FEC performance, the honest answer
    names the burst model used, and a design house that can produce that model has
    something to sell beyond the RTL.</div>""")
    s.append(plot([math.log10(b) for b in (1e-3, 3e-4, 1e-4, 3e-5, 1e-5)],
                  [("log10 P(uncorrectable)",
                    [math.log10(max(cw_fail(b), 1e-300))
                     for b in (1e-3, 3e-4, 1e-4, 3e-5, 1e-5)])],
                  "log10 pre-FEC BER", "log10 P(codeword fails)",
                  "The FEC waterfall for RS(544,514), computed from the binomial tail. "
                  "Note the slope: near the knee, a 1 dB change in SNR moves the output "
                  "by many decades."))
    return "\n".join(s)
