"""Design projects (workspace) and planning reports.

A report has nine fixed sections. Every statement is labelled by origin:
  [measured]     computed from stored image bytes
  [reviewed]     human-entered or human-reviewed interpretation
  [AI-suggested] machine suggestion, not reviewed
  [user note]    the project owner's own words
  [system]       rule-based summary generated by this program -- not historical fact
Historical context appears with its verification status; unverified or
hypothetical items are never phrased as facts.
"""
from __future__ import annotations

import html
import json
import sqlite3
from collections import Counter

from .assets import AssetRepo
from .research import ClaimRepo, ContextRepo, FeatureRepo
from .timeutil import utcnow

CATEGORICAL = ("orientation", "brightness_level", "contrast_level", "colorfulness_level",
               "dominant_hue")
LABEL = {"auto_measured": "measured", "human_entered": "reviewed", "human_reviewed": "reviewed",
         "ai_suggested": "AI-suggested"}


class ProjectError(ValueError):
    pass


class ProjectRepo:
    FIELDS = ("title", "brief", "target_audience", "medium", "constraints", "direction_notes",
              "excluded_styles", "final_review")
    LIST_FIELDS = ("reference_genres", "reference_periods", "reference_regions")

    def __init__(self, conn: sqlite3.Connection):
        self.conn = conn

    def create(self, title: str, **fields) -> int:
        if not title or not title.strip():
            raise ProjectError("project title is required")
        now = utcnow()
        data = {k: fields.get(k) for k in self.FIELDS if k != "title"}
        lists = {k: json.dumps(fields.get(k) or [], ensure_ascii=False) for k in self.LIST_FIELDS}
        cols = ["title", *data, *lists, "created_at", "updated_at"]
        vals = [title.strip(), *data.values(), *lists.values(), now, now]
        with self.conn:
            cur = self.conn.execute(
                f"INSERT INTO design_projects ({', '.join(cols)}) VALUES ({', '.join('?' * len(cols))})", vals)
        return cur.lastrowid

    def update(self, project_id: int, **fields) -> dict:
        self._require(project_id)
        sets, args = [], []
        for k, v in fields.items():
            if k in self.FIELDS:
                sets.append(f"{k}=?")
                args.append(v)
            elif k in self.LIST_FIELDS:
                sets.append(f"{k}=?")
                args.append(json.dumps(v or [], ensure_ascii=False))
            else:
                raise ProjectError(f"unknown project field {k!r}")
        if sets:
            sets.append("updated_at=?")
            args.append(utcnow())
            with self.conn:
                self.conn.execute(f"UPDATE design_projects SET {', '.join(sets)} WHERE id=?",
                                  args + [project_id])
        return self.get(project_id)

    def _require(self, project_id: int) -> dict:
        row = self.conn.execute("SELECT * FROM design_projects WHERE id=?", (project_id,)).fetchone()
        if row is None:
            raise ProjectError(f"project {project_id} not found")
        return dict(row)

    def get(self, project_id: int) -> dict:
        p = self._require(project_id)
        for k in self.LIST_FIELDS:
            p[k] = json.loads(p[k])
        p["assets"] = [dict(r) for r in self.conn.execute(
            "SELECT * FROM project_assets WHERE project_id=? ORDER BY group_name, added_at, asset_id",
            (project_id,))]
        p["contexts"] = [dict(r) for r in self.conn.execute(
            "SELECT * FROM project_contexts WHERE project_id=? ORDER BY context_id", (project_id,))]
        p["features"] = [dict(r) for r in self.conn.execute(
            "SELECT * FROM project_features WHERE project_id=? ORDER BY feature_type, feature_value",
            (project_id,))]
        p["notes"] = [dict(r) for r in self.conn.execute(
            "SELECT * FROM project_notes WHERE project_id=? ORDER BY id", (project_id,))]
        p["reports"] = [dict(r) for r in self.conn.execute(
            "SELECT id, format, generated_at, reviewed FROM project_reports WHERE project_id=? ORDER BY id",
            (project_id,))]
        return p

    def all(self) -> list[dict]:
        return [dict(r) for r in self.conn.execute(
            """SELECT p.*, (SELECT COUNT(*) FROM project_assets a WHERE a.project_id=p.id) AS asset_count
               FROM design_projects p ORDER BY p.updated_at DESC, p.id DESC""")]

    def add_asset(self, project_id: int, asset_id: str, group: str = "default", note: str | None = None) -> None:
        self._require(project_id)
        if AssetRepo(self.conn).get(asset_id) is None:
            raise ProjectError(f"asset {asset_id} not found")
        with self.conn:
            self.conn.execute(
                "INSERT OR REPLACE INTO project_assets (project_id, asset_id, group_name, note, added_at) "
                "VALUES (?,?,?,?,?)", (project_id, asset_id, group or "default", note, utcnow()))
            self.conn.execute("UPDATE design_projects SET updated_at=? WHERE id=?", (utcnow(), project_id))

    def remove_asset(self, project_id: int, asset_id: str) -> None:
        with self.conn:
            self.conn.execute("DELETE FROM project_assets WHERE project_id=? AND asset_id=?",
                              (project_id, asset_id))

    def add_context(self, project_id: int, context_id: int, note: str | None = None) -> None:
        self._require(project_id)
        if ContextRepo(self.conn).get(context_id) is None:
            raise ProjectError(f"context {context_id} not found")
        with self.conn:
            self.conn.execute("INSERT OR REPLACE INTO project_contexts VALUES (?,?,?,?)",
                              (project_id, context_id, note, utcnow()))

    def add_feature(self, project_id: int, feature_type: str, feature_value: str, note: str | None = None) -> None:
        self._require(project_id)
        with self.conn:
            self.conn.execute("INSERT OR REPLACE INTO project_features VALUES (?,?,?,?)",
                              (project_id, feature_type, feature_value, note))

    def add_note(self, project_id: int, body: str) -> int:
        self._require(project_id)
        if not body or not body.strip():
            raise ProjectError("note is empty")
        with self.conn:
            cur = self.conn.execute("INSERT INTO project_notes (project_id, body, created_at) VALUES (?,?,?)",
                                    (project_id, body.strip(), utcnow()))
        return cur.lastrowid

    # -- report ----------------------------------------------------------------------
    def build_report(self, project_id: int) -> dict:
        p = self.get(project_id)
        assets_repo, features = AssetRepo(self.conn), FeatureRepo(self.conn)
        contexts, claims = ContextRepo(self.conn), ClaimRepo(self.conn)
        refs, open_items, cautions = [], [], []
        measured: Counter = Counter()
        semantic: list[dict] = []
        per_group: dict[str, Counter] = {}
        for pa in p["assets"]:
            a = assets_repo.get(pa["asset_id"])
            if a is None:
                open_items.append(f"Asset {pa['asset_id']} no longer exists.")
                continue
            policy = self._policy(a)
            year = (f"{a['year_start']}" if a["year_start"] == a["year_end"] else
                    f"{a['year_start']}-{a['year_end']}") if a["year_start"] is not None else None
            refs.append({"id": a["id"], "group": pa["group_name"], "title": a["title"] or a["alt"],
                         "year": year, "year_basis": a["year_basis"], "creator": a["creator"],
                         "country": a["country"], "source_page_url": a["source_page_url"],
                         "original_url": a["url"], "rights_status": policy,
                         "local_file": a["abs_path"] if a["download_status"] == "downloaded" else None,
                         "note": pa["note"]})
            if year is None:
                open_items.append(f"{a['id']}: year unknown -- not placed in any period.")
            if policy != "allowed":
                cautions.append(f"{a['id']}: rights status '{policy}' -- use as reference only; "
                                "do not reproduce without clearance.")
            if a["download_status"] != "downloaded":
                open_items.append(f"{a['id']}: no local file ({a['download_status']}).")
            feats = features.for_asset(a["id"])
            if not feats:
                open_items.append(f"{a['id']}: no visual features recorded yet.")
            group = per_group.setdefault(pa["group_name"], Counter())
            for f in feats:
                if f["kind"] == "measured" and f["feature_type"] in CATEGORICAL:
                    measured[(f["feature_type"], f["feature_value"])] += 1
                    group[(f["feature_type"], f["feature_value"])] += 1
                elif f["kind"] == "semantic":
                    semantic.append({"asset_id": a["id"], "type": f["feature_type"],
                                     "value": f["feature_value"], "label": LABEL[f["review_status"]],
                                     "tool": f["tool"]})
        n = len(refs)
        common = [{"feature": k[0], "value": k[1], "count": c, "of": n, "label": "measured"}
                  for k, c in sorted(measured.items(), key=lambda kv: (-kv[1], kv[0])) if n and c / n >= 0.5]
        differences = []
        if len(per_group) > 1:
            for g, counter in sorted(per_group.items()):
                top = [f"{k[0]}={k[1]} ({c})" for k, c in counter.most_common(4)]
                differences.append({"group": g, "top_measured": top})
        else:
            spread: dict[str, set] = {}
            for (ft, fv) in measured:
                spread.setdefault(ft, set()).add(fv)
            differences = [{"feature": ft, "values_seen": sorted(vs)} for ft, vs in sorted(spread.items())
                           if len(vs) > 1]
        ctx_out, evidence = [], {}
        for pc in p["contexts"]:
            c = contexts.get(pc["context_id"])
            ctx_out.append({"id": c["id"], "title": c["title"], "period": [c["start_year"], c["end_year"]],
                            "status": c["verification_status"], "description": c["description"],
                            "alternatives": c["alternative_interpretations"],
                            "phrase": "documented" if c["verification_status"] == "verified" else
                            "reported, partially supported" if c["verification_status"] == "partially_supported"
                            else "unconfirmed -- treat as a lead, not a fact"})
            if c["verification_status"] in ("unverified", "hypothesis"):
                open_items.append(f"Context '{c['title']}' is {c['verification_status']}: needs sources.")
            if c["verification_status"] == "contradicted":
                cautions.append(f"Context '{c['title']}' is contradicted by sources; do not rely on it.")
            for claim in c["claims"]:
                for e in claim["evidence"]:
                    evidence.setdefault(e["source_id"], {"title": e["title"], "type": e["source_type"],
                                                         "url": e["url"], "author": e["author"],
                                                         "uses": []})["uses"].append(
                        {"claim": claim["claim_text"], "claim_status": claim["verification_status"],
                         "relation": e["relation"], "access_level": e["access_level"],
                         "locator": e["locator"]})
            for s in c["sources"]:
                evidence.setdefault(s["id"], {"title": s["title"], "type": s["source_type"],
                                              "url": s["url"], "author": s["author"], "uses": []})
        for claim in claims.pending_review():
            if claim["context_id"] in {pc["context_id"] for pc in p["contexts"]}:
                open_items.append(f"Claim #{claim['id']} is {claim['verification_status']}: "
                                  f"\"{claim['claim_text'][:80]}\"")
        directions = [{"label": "user note", "text": p["direction_notes"]}] if p["direction_notes"] else []
        directions += [{"label": "user note", "text": nt["body"]} for nt in p["notes"]]
        for c in common:
            directions.append({"label": "system", "text": self._principle(c)})
        for f in p["features"]:
            directions.append({"label": "user note",
                               "text": f"Reference feature {f['feature_type']}={f['feature_value']}"
                                       + (f": {f['note']}" if f["note"] else "")})
        if n < 5:
            cautions.append(f"Only {n} reference(s): shared features describe this selection, not a trend.")
        if p["excluded_styles"]:
            cautions.append(f"Excluded styles/constraints from the brief: {p['excluded_styles']}")
        cautions.append("Borrow principles (proportion, contrast, rhythm, hierarchy), not recognisable "
                        "compositions or marks of a specific work.")
        if any(s["label"] == "AI-suggested" for s in semantic):
            open_items.append("Some interpretations are AI-suggested and unreviewed.")
        return {
            "schema": "design_project_report/1", "project_id": p["id"], "generated_at": utcnow(),
            "sections": {
                "1_goal": {"title": p["title"], "brief": p["brief"], "audience": p["target_audience"],
                           "medium": p["medium"], "constraints": p["constraints"],
                           "reference_genres": p["reference_genres"],
                           "reference_periods": p["reference_periods"],
                           "reference_regions": p["reference_regions"]},
                "2_references": refs,
                "3_common_features": {"measured": common, "interpretations": semantic},
                "4_different_approaches": differences,
                "5_context": ctx_out,
                "6_evidence": [dict(v, id=k) for k, v in sorted(evidence.items())],
                "7_directions": directions,
                "8_cautions": cautions,
                "9_open_questions": open_items,
            },
        }

    def _policy(self, a: dict) -> str:
        from .registry import Registry
        reg = Registry(self.conn)
        return reg.effective_image_policy(a["id"], reg.get(a["source_id"]))["status"]

    @staticmethod
    def _principle(c: dict) -> str:
        f, v, k, n = c["feature"], c["value"], c["count"], c["of"]
        hints = {
            "brightness_level": f"{k}/{n} references measure '{v}' overall brightness -- consider the "
                                f"same tonal key as a starting point.",
            "contrast_level": f"{k}/{n} references measure '{v}' contrast -- decide early whether the "
                              f"design keeps or breaks that contrast range.",
            "colorfulness_level": f"{k}/{n} references are '{v}' in colourfulness -- a palette "
                                  f"discipline worth testing.",
            "dominant_hue": f"{k}/{n} references have a '{v}' dominant hue.",
            "orientation": f"{k}/{n} references are {v}-format images.",
        }
        return hints.get(f, f"{k}/{n} references share {f}={v}.")

    def save_report(self, project_id: int, fmt: str = "markdown") -> tuple[int, str]:
        report = self.build_report(project_id)
        if fmt == "json":
            content = json.dumps(report, ensure_ascii=False, indent=2)
        elif fmt == "markdown":
            content = render_markdown(report)
        elif fmt == "html":
            content = render_html(report)
        else:
            raise ProjectError("format must be markdown|json|html")
        with self.conn:
            cur = self.conn.execute("INSERT INTO project_reports (project_id, format, content, generated_at) "
                                    "VALUES (?,?,?,?)", (project_id, fmt, content, utcnow()))
        return cur.lastrowid, content


def render_markdown(r: dict) -> str:
    s = r["sections"]
    g = s["1_goal"]
    out = [f"# Design planning report: {g['title']}", "",
           f"_Generated {r['generated_at']}. Labels: [measured] computed from image bytes; "
           "[reviewed] human interpretation; [AI-suggested] unreviewed machine suggestion; "
           "[user note] project owner; [system] rule-based summary, not historical fact._", "",
           "## 1. Project goal", ""]
    for k in ("brief", "audience", "medium", "constraints"):
        out.append(f"- **{k}**: {g[k] if g[k] else '(not set)'}")
    for k in ("reference_genres", "reference_periods", "reference_regions"):
        out.append(f"- **{k}**: {', '.join(g[k]) if g[k] else '(not set)'}")
    out += ["", "## 2. References", ""]
    if not s["2_references"]:
        out.append("(no references selected)")
    for ref in s["2_references"]:
        out.append(f"- `{ref['id']}` [{ref['group']}] {ref['title'] or '(untitled)'} -- "
                   f"year: {ref['year'] or 'unknown'}"
                   + (f" ({ref['year_basis']})" if ref["year_basis"] else "")
                   + f"; creator: {ref['creator'] or 'unknown'}; rights: {ref['rights_status']}; "
                     f"source: {ref['source_page_url'] or ref['original_url']}")
    out += ["", "## 3. Shared visual features", ""]
    if not s["3_common_features"]["measured"]:
        out.append("(no measured feature is shared by at least half of the references)")
    for c in s["3_common_features"]["measured"]:
        out.append(f"- [measured] {c['feature']} = {c['value']} ({c['count']}/{c['of']})")
    for i in s["3_common_features"]["interpretations"]:
        out.append(f"- [{i['label']}] {i['asset_id']}: {i['type']} = {i['value']}"
                   + (f" (tool: {i['tool']})" if i["tool"] else ""))
    out += ["", "## 4. Different design approaches", ""]
    if not s["4_different_approaches"]:
        out.append("(not enough measured variation to compare)")
    for d in s["4_different_approaches"]:
        if "group" in d:
            out.append(f"- group **{d['group']}**: {', '.join(d['top_measured']) or '(no measurements)'}")
        else:
            out.append(f"- {d['feature']}: {', '.join(d['values_seen'])}")
    out += ["", "## 5. Historical and cultural context", ""]
    if not s["5_context"]:
        out.append("(no context records linked)")
    for c in s["5_context"]:
        period = "-".join(str(x) for x in c["period"] if x is not None) or "period unknown"
        out.append(f"- **{c['title']}** ({period}) -- status: `{c['status']}` ({c['phrase']}). "
                   f"{c['description']}")
        if c["alternatives"]:
            out.append(f"  - alternative interpretations: {c['alternatives']}")
    out += ["", "## 6. Evidence", ""]
    if not s["6_evidence"]:
        out.append("(no sources linked)")
    for e in s["6_evidence"]:
        out.append(f"- {e['title']} ({e['type']}{', ' + e['author'] if e['author'] else ''})"
                   + (f" <{e['url']}>" if e["url"] else ""))
        for u in e["uses"]:
            out.append(f"  - {u['relation']} (read: {u['access_level']}"
                       + (f", {u['locator']}" if u["locator"] else "")
                       + f") claim [{u['claim_status']}]: {u['claim']}")
    out += ["", "## 7. Proposed design directions", ""]
    if not s["7_directions"]:
        out.append("(no direction notes yet)")
    for d in s["7_directions"]:
        out.append(f"- [{d['label']}] {d['text']}")
    out += ["", "## 8. Cautions", ""] + [f"- {c}" for c in s["8_cautions"]]
    out += ["", "## 9. Open questions and further research", ""]
    out += [f"- {o}" for o in s["9_open_questions"]] or ["(none recorded)"]
    return "\n".join(out) + "\n"


def render_html(r: dict) -> str:
    md = render_markdown(r)
    body = []
    for line in md.splitlines():
        esc = html.escape(line)
        if line.startswith("# "):
            body.append(f"<h1>{esc[2:]}</h1>")
        elif line.startswith("## "):
            body.append(f"<h2>{esc[3:]}</h2>")
        elif line.startswith("  - "):
            body.append(f"<p class='sub'>&bull; {esc[4:]}</p>")
        elif line.startswith("- "):
            body.append(f"<p>&bull; {esc[2:]}</p>")
        elif line.strip():
            body.append(f"<p>{esc}</p>")
    return ("<!doctype html><meta charset='utf-8'><title>Design planning report</title>"
            "<style>body{font-family:system-ui,sans-serif;max-width:860px;margin:2rem auto;padding:0 1rem;"
            "line-height:1.5}.sub{margin-left:1.5rem;color:#555}</style>" + "\n".join(body))
